---
- name: My fedora44 configuration
  hosts: localhost
  connection: local

  roles:
    - vscode
    - flatpak
    - gnome-extensions
    - dnf
    - syncthing
    - ssh-client
    - git

  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "mishaid-{{ ansible_facts['board_name'] }}"
        use: systemd

# TODO: Установка модулей VSCode???
# TODO: Установка курсора и значков в Gnome
