---
- name: My fedora44 configuration
  hosts: localhost
  connection: local

  roles:
    - vscode
    - flatpak
    - gnome-extensions
    - dnf
    - syncthing
    - ssh-client
    - git

  # tasks:
  #   - name: Display facts
  #     ansible.builtin.debug:
  #       msg: "{{ ansible_facts }}"

# TODO: hostname на основе board_name из ansible_facts
# TODO: Установка модулей VSCode???
# TODO: Установка курсора и значков в Gnome
