# VSCoduim
- name: Add VSCoduim repo
  ansible.builtin.copy:
    src: files/vscodium.repo
    dest: /etc/yum.repos.d/vscodium.repo
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Install VSCoduim
  ansible.builtin.dnf:
    name: codium
    state: present
  become: true

- name: Create VSCoduim config folder
  ansible.builtin.file:
    path: /home/mishaid/.config/VSCodium/User
    state: directory
    owner: mishaid
    group: mishaid
    mode: '700'

- name: Configure VSCoduim
  ansible.builtin.copy:
    src: files/vscode_settings.json
    dest: /home/mishaid/.config/VSCodium/User/settings.json
    owner: mishaid
    group: mishaid
    mode: '0644'
