# Flatpak general
- name: Set Flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
